### PR TITLE
enabled to pass header values to request headers

### PR DESCRIPTION
**Pull request by deadcheat**
i want set some values to request headers from a request to widebullet server.
thought to use  when call some apis to use different tokens to authorize.

i added "ProxyPassHeaders" settings to config, and part using that.
sorry to bother you, please indicate how work if there are any solutions to do that.

thank you.

### CODE REVIEW

**Comment by deadcheat** [comment]
property name "ProxyPassHeaders" maybe unsuitable.

**Comment by cubicdaiya** [comment]
Why don't you pass all headers by default and overwrite by **ProxySetHeaders**?

**Comment by deadcheat** [comment]
you mean two points below?
- Not adding "ProxyPassHeaders",  fix to pass all header to request sent to destination
- Then, overwrite using ProxySetHeaders

In that case, i'm not satisfied anything.
My purpose is to enable handle a value from one header to another header, sometimes that named different from origin's.

Or, if you meant to add a process transfer all header value to request to destination,
ofcourse i can do that.

**Comment by cubicdaiya** [comment]
> Not adding "ProxyPassHeaders", fix to pass all header to request sent to destination
> Then, overwrite using ProxySetHeaders

Yes.

> My purpose is to enable handle a value from one header to another header, sometimes that named different from origin's.

I would not add such as the feature. Sorry.

**Comment by deadcheat** [comment]
ok, thanks.

**Pull request closed without merging**
